
CREATE DATABASE SPARTAN;
use SPARTAN;

CREATE TABLE  APLICACIONES (
   ID_APLICACION int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   APLICACION  varchar(30) NOT NULL,
   FECHA_CREACION DATE
);

INSERT INTO  APLICACIONES ( APLICACION ,  FECHA_CREACION) VALUES ('3KAVIATION', SYSDATE());

CREATE TABLE  ROLES  (
   ID_ROL int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   ID_APLICACION int NOT NULL,
   ROL varchar(25) NOT NULL,
   FECHA_CREACION DATE,
   FOREIGN KEY (ID_APLICACION) REFERENCES APLICACIONES(ID_APLICACION)
);

CREATE TABLE SECCIONES ( 
   ID_SECCION int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   ID_APLICACION int NOT NULL,
   SECCION varchar(40) NOT NULL,
   FOREIGN KEY (ID_APLICACION) REFERENCES APLICACIONES(ID_APLICACION)
);

--INSERT INTO  SECCIONES ( ID_APLICACION ,  SECCION) VALUES ('3KAVIATION', SYSDATE);

CREATE TABLE USUARIOS (
ID_USUARIO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_APLICACION int NOT NULL,
ID_ROL int NOT NULL,
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
CORREO VARCHAR(40),
NICK VARCHAR(25),
PASS VARCHAR(25),
FOREIGN KEY (ID_APLICACION) REFERENCES APLICACIONES(ID_APLICACION),
FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);


CREATE TABLE PERMISOS (
  ID_PERMISO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_APLICACION int NOT NULL,
  ID_SECCION int NOT NULL,
  ID_ROL int NOT NULL,
  P_VER VARCHAR(1),
  P_MODIFICAR VARCHAR(1),
  P_TODO VARCHAR(1),
  FOREIGN KEY (ID_APLICACION) REFERENCES APLICACIONES(ID_APLICACION),
  FOREIGN KEY (ID_SECCION) REFERENCES SECCIONES(ID_SECCION),
  FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE AVI_AERONAVES(
  ID_AERONAVE int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(20),
  TIPO VARCHAR(20),
  CONSUMO FLOAT
);

CREATE TABLE AVI_FIRMAS(
  ID_FIRMA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRMA_RUTA VARCHAR(30)
);


CREATE TABLE AVI_PLAN_VUELO(
  ID_PLAN int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_AERONAVE int NOT NULL,
  AERO_SALIDA VARCHAR(25),
  AERO_LLEGADA VARCHAR(25),
  PROPIETARIO VARCHAR(25),
  HORA_SALIDA DATE,
  HORA_LLEGADA DATE,
  FECHA_VIAJE DATE,
  DECLA_SANITARIA TEXT,
  ESTATUS VARCHAR(1) DEFAULT '0',
  ID_FIRMA int NOT NULL,
  FOREIGN KEY (ID_AERONAVE) REFERENCES AERONAVES(ID_AERONAVE),
  FOREIGN KEY (ID_FIRMA) REFERENCES FIRMAS(ID_FIRMAS)
);


-- AQUÍ SE AGREGA A LAS PERSONAS Y LOS CARGOS
CREATE TABLE AVI_TRIPULACION(
  ID_TRIPULACION int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_PLAN INT NOT NULL,
  NOMBRE VARCHAR(30),
  APELLIDO VARCHAR(30),
  FUNCION VARCHAR(25),
  LICENCIA  VARCHAR(20),
  NACIONALIDAD VARCHAR(30),
  FECHA_NAC DATE,
  PASAPORTE VARCHAR(30),
  EXP_PASAPORTE DATE,
  FOREIGN KEY (ID_PLAN) REFERENCES AVI_PLAN_VUELO(ID_PLAN)
);

CREATE TABLE AVI_PASAJEROS(
  ID_PASAJERO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_PLAN INT NOT NULL,
  NOMBRE VARCHAR(30),
  APELLIDO VARCHAR(30),
  NACIONALIDAD VARCHAR(30),
  FECHA_NAC DATE,
  TIPO_DOCUMENTO  VARCHAR(30),
  DOCUMENTO VARCHAR(30),
  EXP_DOCUMENTO DATE,
  FOREIGN KEY (ID_PLAN) REFERENCES AVI_PLAN_VUELO(ID_PLAN)
);



